### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by Decem-Y** [yuanze-lin/Learnable_Regions#1]
good work！！！
your project looks very interesting, do you have a date for it's release?

**Comment by yuanze-lin** [comment]
> good work！！！
your project looks very interesting, do you have a date for it's release?

Hello, thank you for your attention, I'm now working on other projects and catching up with incoming conferences, I'll release the code soon

**Comment by Decem-Y** [comment]
> > good work！！！
> > your project looks very interesting, do you have a date for it's release?
> 
> Hello, thank you for your attention, I'm now working on other projects and catching up with incoming conferences, I'll release the code soon

Thanks for the reply, I have one more question, is there a suggested training dataset to use?

**Comment by yuanze-lin** [comment]
> Thanks for the reply, I have one more question, is there a suggested training dataset to use?

You're welcome, actually, I think there are some options, it depends on you: 

(1) You can collect the images from a free image website, like [unsplash](https://unsplash.com/). 
(2) You can use the [TEdBench](https://github.com/imagic-editing/imagic-editing.github.io/tree/main/tedbench).
(3) You can also adopt the dataset from [instruct-pix2pix](https://github.com/timothybrooks/instruct-pix2pix).

If you want to evaluate your method, I think you can use TEdBench or the collected images from unsplash.

**Comment by Decem-Y** [comment]
> > Thanks for the reply, I have one more question, is there a suggested training dataset to use?
> 
> You're welcome, actually, I think there are some options, it depends on you:
> 
> (1) You can collect the images from a free image website, like [unsplash](https://unsplash.com/). (2) You can use the [TEdBench](https://github.com/imagic-editing/imagic-editing.github.io/tree/main/tedbench). (3) You can also adopt the dataset from [instruct-pix2pix](https://github.com/timothybrooks/instruct-pix2pix).
> 
> If you want to evaluate your method, I think you can use TEdBench or the collected images from unsplash.

Thank you for your guidance, it was very helpful for me. I wish you success in your incoming conferences.

**Comment by yuanze-lin** [comment]
> > > Thanks for the reply, I have one more question, is there a suggested training dataset to use?
> > 
> > 
> > You're welcome, actually, I think there are some options, it depends on you:
> > (1) You can collect the images from a free image website, like [unsplash](https://unsplash.com/). (2) You can use the [TEdBench](https://github.com/imagic-editing/imagic-editing.github.io/tree/main/tedbench). (3) You can also adopt the dataset from [instruct-pix2pix](https://github.com/timothybrooks/instruct-pix2pix).
> > If you want to evaluate your method, I think you can use TEdBench or the collected images from unsplash.
> 
> Thank you for your guidance, it was very helpful for me. I wish you success in your incoming conferences.

Very sorry for the delay in releasing the code. The code has been released now, so have fun playing with it! :)
