### ISSUE TITLE
Runwayml is down

### ISSUE THREAD

**Issue by jungeun122333** [yuanze-lin/Learnable_Regions#3]
Dear authors, thank you for your impressive work.
However, I found out that the inpainting model from runwayml has been closed.
Could you suggest any alternatives?
Thank you in advance.

This is the error message:
```
Initializing diffusion model:  runwayml/stable-diffusion-inpainting
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-66e2539e-07d9be71002211260af4affe;8f8397e1-a462-451d-96e7-ce2e99df5ea7)

Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-inpainting/revision/fp16.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
```

**Comment by yuanze-lin** [comment]
Hello JungEun, 

Thank you for your interest in our work. Unfortunately, it seems that Runway has recently discontinued their diffusion models, including the impressive inpainting models. 

As I need to focus on another project at the moment, could you try using the inpainting model released by StabilityAI? You can find it here: https://huggingface.co/stabilityai/stable-diffusion-2-inpainting.

**Comment by yuanze-lin** [comment]
If you have any further questions, please feel free to open an issue.

**Comment by yuanze-lin** [comment]
For your convenience, you can set `--diffusion_model_path 'stabilityai/stable-diffusion-2-inpainting'` in the command. I've also updated the scripts in the repository, so please use the latest version.
