### ISSUE TITLE
Inaccessibility to the model

### ISSUE THREAD

**Issue by Sara068** [yuanze-lin/Learnable_Regions#4]
Dear Authors,
Thank you for your outstanding work on this project. I truly appreciate the effort and innovation you have put into it.
However, I recently discovered that the inpainting model from RunwayML is no longer available. I need to run this model for my own project, so I would greatly appreciate it if you could suggest any suitable alternatives.
Thank you very much for your assistance and guidance.

This is the error message:

Initializing diffusion model:  runwayml/stable-diffusion-inpainting
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-66e2539e-07d9be71002211260af4affe;8f8397e1-a462-451d-96e7-ce2e99df5ea7)

Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-inpainting/revision/fp16.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

**Comment by yuanze-lin** [comment]
Hello Zeinab, 

Thank you for your interest in our work. Unfortunately, it seems that Runway has recently discontinued their diffusion models, including the impressive inpainting models. 

At the moment, I need to focus on another project, but I recommend trying the inpainting model released by Stability AI (link: https://huggingface.co/stabilityai/stable-diffusion-2-inpainting).

**Comment by yuanze-lin** [comment]
If you have any further questions, please feel free to open an issue.

**Comment by yuanze-lin** [comment]
For your convenience, you can set `--diffusion_model_path 'stabilityai/stable-diffusion-2-inpainting'` in the command. I've also updated the scripts in the repository, so please use the latest version.

**Comment by Sara068** [comment]
Hello,
Thank you very much for the update and the clarification!

Best regards,
